### ISSUE TITLE
A reoccurring issue with app_style diffusion

### ISSUE THREAD

**Issue by strn2** [spparks/spparks#6]
Hello, 

I've been trying to run a very simple sample simulation using the diffusion module. Running my input file gives me an error in my output. Below, I've copied and pasted my input file, in.diff and its output. 

variable SEED equal                 1

variable T equal                 0.25

variable DT equal 400.0

seed             ${SEED}

app_style diffusion linear hop

dimension        2

boundary p p p

lattice          tri 3
region           box block 0 10 0 10 0 10
create_box       box
create_sites     box

barrier hop 0.1

:
solve_style tree

sector yes
diag_style       energy
temperature      ${T}
stats            10.0

run             ${DT}`

After running  `mpirun -np 4 spk_mpi < in.diff` : 

`SPPARKS (24 June 2021)
Created box = (0 0 0) to (30 51.9615 30)
  2 by 2 by 1 processor grid
Creating sites ...
  200 sites
  200 sites have 6 neighbors
ERROR: Unrecognized command (../app_diffusion.cpp:226)
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[8765,1],3]
  Exit code:    1
--------------------------------------------------------------------------`

I'm unsure why this keeps happening. Any help would be appreciated. Thank you!

**Comment by jamitch-snl** [comment]
We have looked at the problem you reported; It appears you are hitting two different but small errors in your input.

1. The particular runtime error you are showing is arising from an invalid command in the input script.  From what you are showing its difficult to tell the exact error since what is shown is a cut/paste.  Below I have attached/included an input script which works -- created on the basis of what you showed.  You can tweak/modify this as you need.
2. Your input script was missing initialization of sites -- many of the apps will emit a runtime error if sites are not initialized to allowable values before running the app.  An example showing how to initialize the sites is included in attached script below; you can set site values to whatever you like accept that they should be >0.

Also attached is runtime log file.  Suggest comparing the version of spparks at the start log (SPPARKS (24 June 2021)) with the version you are running (will show in your runtime log).

[in_tri.txt](https://github.com/spparks/spparks/files/8143730/in_tri.txt)
[log.txt](https://github.com/spparks/spparks/files/8143731/log.txt)
